import type { BuildingDef, BuildingType } from './types';

export const MAP_W = 30;
export const MAP_H = 30;
export const START_ENERGY = 3;
export const TURN_CAP = 80;
export const MIN_TERRITORY = 60; // target floor for equalized buildable cells per player (2P)
export const MAX_TERRITORY = 80; // cap so territories stay ~60-80 and leave sea/neutral

// Faction flavor (cosmetic): name + accent color
export const FACTIONS = [
  { id: 'azure', name: 'Azure Fleet', color: '#3fb6ff' },
  { id: 'crimson', name: 'Crimson Armada', color: '#ff5a5a' },
  { id: 'amber', name: 'Amber Legion', color: '#ffcf4d' },
  { id: 'viridian', name: 'Viridian Pact', color: '#52e0a0' },
] as const;

// Central balance table. Plot sizes & core effects honor the design brief exactly.
export const BUILDINGS: Record<BuildingType, BuildingDef> = {
  base: {
    type: 'base',
    name: 'Command Base',
    short: 'HQ',
    w: 2,
    h: 2,
    cost: 6,
    hpPerCell: 2,
    category: 'hq',
    requiresResearch: false,
    maxCount: 1,
    energy: 2,
    desc: 'Your headquarters. Generates +2⚡ per turn. Armored (2 HP per cell). Only one at a time — if destroyed you can rebuild it (6⚡). You are eliminated only when no Base remains and you cannot rebuild.',
    tagline: 'The heart of your fleet.',
  },
  silo: {
    type: 'silo',
    name: 'Missile Silo',
    short: 'SIL',
    w: 1,
    h: 1,
    cost: 4,
    hpPerCell: 1,
    category: 'weapon',
    requiresResearch: false,
    cooldown: 1,
    attackW: 1,
    attackH: 1,
    desc: 'Fires one single-cell missile each turn. Cheap, reliable bombardment.',
    tagline: 'One shot, every turn.',
  },
  artillery: {
    type: 'artillery',
    name: 'Artillery Battery',
    short: 'ART',
    w: 2,
    h: 2,
    cost: 6,
    hpPerCell: 1,
    category: 'weapon',
    requiresResearch: false,
    cooldown: 2,
    attackW: 2,
    attackH: 2,
    desc: 'Saturates a 2×2 area. Devastating against clustered structures. Reloads every 2 turns.',
    tagline: 'Area denial.',
  },
  napalm: {
    type: 'napalm',
    name: 'Napalm Battery',
    short: 'NAP',
    w: 2,
    h: 1,
    cost: 8,
    hpPerCell: 1,
    category: 'weapon',
    requiresResearch: false,
    cooldown: 2,
    attackW: 3,
    attackH: 1,
    desc: 'Looses a wall of fire across three cells in a row. Press R to rotate the line. Reloads every 2 turns.',
    tagline: 'Burn it down.',
  },
  powerplant: {
    type: 'powerplant',
    name: 'Power Plant',
    short: 'PWR',
    w: 3,
    h: 1,
    cost: 5,
    hpPerCell: 1,
    category: 'economy',
    requiresResearch: false,
    maxCount: 2,
    energy: 1,
    desc: 'Generates +1⚡ per turn (boosted to +2⚡ with an active Research Station). Cannot work without a command base. Build up to two.',
    tagline: 'Fuel the war machine.',
  },
  research: {
    type: 'research',
    name: 'Research Station',
    short: 'RES',
    w: 2,
    h: 1,
    cost: 5,
    hpPerCell: 2,
    category: 'tech',
    requiresResearch: false,
    maxCount: 1,
    desc: 'Unlocks advanced detection & defense tech. Only one allowed. If destroyed, ALL advanced buildings go offline until rebuilt.',
    tagline: 'Knowledge is power.',
  },
  nuclear: {
    type: 'nuclear',
    name: 'Nuclear Facility',
    short: 'NUK',
    w: 3,
    h: 2,
    cost: 15,
    hpPerCell: 1,
    category: 'weapon',
    requiresResearch: true,
    cooldown: 5,
    attackW: 3,
    attackH: 3,
    irradiates: true,
    desc: 'Launches a warhead obliterating a 3×3 (9-cell) zone and IRRADIATING the terrain — those cells become permanently unbuildable. Free to fire on a 5-turn cooldown.',
    tagline: 'The final argument.',
  },
  // ---- Advanced (require a living Research Station) ----
  radar: {
    type: 'radar',
    name: 'Radar Station',
    short: 'RAD',
    w: 2,
    h: 2,
    cost: 6,
    hpPerCell: 1,
    category: 'detection',
    requiresResearch: true,
    range: 3,
    desc: 'Each of your turns, reveals enemy structures within 3 cells. Line of sight blocked by mountains.',
    tagline: 'See through the fog.',
  },
  sonar: {
    type: 'sonar',
    name: 'Sonar Array',
    short: 'SON',
    w: 2,
    h: 1,
    cost: 5,
    hpPerCell: 1,
    category: 'detection',
    requiresResearch: true,
    cooldown: 2,
    attackW: 3,
    attackH: 3,
    desc: 'Active ping: scans a chosen 3×3 area, revealing the structures hidden there. Recharges every 2 turns.',
    tagline: 'Ping the deep.',
  },
  shield: {
    type: 'shield',
    name: 'Shield Generator',
    short: 'SHD',
    w: 2,
    h: 2,
    cost: 8,
    hpPerCell: 1,
    category: 'defense',
    requiresResearch: true,
    range: 2,
    cooldown: 2,
    desc: 'Projects a hardlight shield over friendly structures within 2 cells, absorbing one hit per structure cell. When a protected cell is hit, only that cell\'s shield is breached and goes on a 2-turn cooldown. Multiple generators do not stack.',
    tagline: 'Hold the line.',
  },
  turret: {
    type: 'turret',
    name: 'Flak Turret',
    short: 'FLK',
    w: 1,
    h: 1,
    cost: 5,
    hpPerCell: 1,
    category: 'defense',
    requiresResearch: true,
    range: 2,
    interceptChance: 0.35,
    desc: 'Has a 35% chance to shoot down an incoming missile within 2 cells. After a successful intercept it must reload for a round. Useless against artillery, napalm and nukes.',
    tagline: 'Point defense online.',
  },
  repair: {
    type: 'repair',
    name: 'Engineering Bay',
    short: 'ENG',
    w: 2,
    h: 1,
    cost: 7,
    hpPerCell: 1,
    category: 'defense',
    requiresResearch: true,
    range: 3,
    cooldown: 3,
    desc: 'Every 3 turns, repairs 1 HP on the most-damaged friendly structure within 3 cells.',
    tagline: 'Patch and rebuild.',
  },
  jammer: {
    type: 'jammer',
    name: 'Signal Jammer',
    short: 'JAM',
    w: 1,
    h: 1,
    cost: 4,
    hpPerCell: 1,
    category: 'detection',
    requiresResearch: true,
    range: 2,
    desc: 'Hides friendly structures within 2 cells from enemy radar and sonar (direct hits still reveal).',
    tagline: 'Ghost in the static.',
  },
};

// Palette order for the build menu, grouped.
export const PALETTE: BuildingType[] = [
  'base',
  'powerplant',
  'silo',
  'napalm',
  'artillery',
  'research',
  'radar',
  'sonar',
  'jammer',
  'shield',
  'turret',
  'repair',
  'nuclear',
];

export const ADVANCED: BuildingType[] = ['radar', 'sonar', 'shield', 'turret', 'repair', 'jammer'];

export function buildingDef(type: BuildingType): BuildingDef {
  return BUILDINGS[type];
}
